### ISSUE TITLE
create a roles property for a user that connects to the roles table via user_role table.

### ISSUE THREAD

**Issue by pchtsp** [baobabsoluciones/cornflow-server#73]
so that we can easily query the roles for a given user without having to make a join or do any operations in python.

**Comment by ggsdc** [comment]
@pchtsp This should already be working with PR #78 . `UserModel `has the following property:

`user_roles = db.relationship("UserRoleModel", cascade="all,delete", backref="users")`

So if we have a user object we can get the list of its assigned roles (objects) doing: `user.user_roles`, if we want to get the id of any role we can do: `user.user_roles[#].role_id`, if we want to get the name of the roles: `user.user_roles[#].role.name`.

I guess that we could improve this with a `@property` method so that we get information in the format that we want, sso we could have something like this:

```
    @property
    def roles(self):
        return {r.role.id: r.role.name for r in self.user_roles}
```

So that we can just use `user.roles` to get a dict of the role id and the role name?

**Comment by ggsdc** [comment]
In this line, what the roles property should give back should aligned with what we use in [Auth.get_permission_for_request()](https://github.com/baobabsoluciones/corn/blob/master/cornflow/shared/authentication.py#L88), so that the roles of the user can be check against the permissions that the roles have on each endpoint/action.
